kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:9092
      schemaRegistry: http://localhost:8081
    #   ksqldbServer: http://localhost:8088
    #   kafkaConnect:
    #     - name: first
    #       address: http://localhost:8083
    #   metrics:
    #     port: 9997
    #     type: JMX

dynamic.config.enabled: true
