


server:
  port: 8181

spring:
  main:
    web-application-type: none
  application:
    name: transaction-producer
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1


transaction-producer:
  fixed-rate: 1000
  topic-name: transactions

debug: false
